### ISSUE TITLE
C2-12828-1 error

### ISSUE THREAD

**Issue by kamilb880** [joel16/VITA-Homebrew-Sorter#2]
Initial app launch (v1.20) resulted in C2-12828-1 error.
FW 3.60 (Enso), app.db and error psp2dmp files attached.

[C2-12828-1.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6357321/C2-12828-1.zip)

**Comment by joel16** [comment]
Does it ever get to the splash screen? Or does it just error out before it even gets there?

**Comment by servandios** [comment]
Same error here (12828), no splash, just the error screen.

**Comment by joel16** [comment]
I think I figured out why you guys are crashing before even getting to the boot screen. Recent versions of vitaGL is dependent on SceShaccCg so you'll need to install and run this https://github.com/OsirizX/ShaRKF00D/releases. Once that is done the app should boot. I'd also recommend updating VITA Homebrew Sorter to v1.21 if you haven't.

**Comment by v1ru555** [comment]
I have the same issue, have 1.21 and i always had libshacccg.suprx in my data folder due to GTASA. I see the Kyuhen contest screen, then C2-12828-1 crash.

**Comment by joel16** [comment]
> I have the same issue, have 1.21 and i always had libshacccg.suprx in my data folder due to GTASA. I see the Kyuhen contest screen, then C2-12828-1 crash.

Your issue is different since you actually get to the splash screen. Can you send your app.db?

**Comment by v1ru555** [comment]
> > I have the same issue, have 1.21 and i always had libshacccg.suprx in my data folder due to GTASA. I see the Kyuhen contest screen, then C2-12828-1 crash.
> 
> Your issue is different since you actually get to the splash screen. Can you send your app.db?

Attached
[app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6372263/app.zip)

**Comment by joel16** [comment]
> > > I have the same issue, have 1.21 and i always had libshacccg.suprx in my data folder due to GTASA. I see the Kyuhen contest screen, then C2-12828-1 crash.
> > 
> > 
> > Your issue is different since you actually get to the splash screen. Can you send your app.db?
> 
> Attached
> [app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6372263/app.zip)

Okay this was happening because one of the apps "power" (I believe you're on a PS TV?) doesn't have a title, nor a titleId or a reservedID. Now if it doesn't find the first reserved ID, it'll look for the second, so this time it should work. If you can confirm its fixed please try this and let me know: 
[VITA-Homebrew-Sorter-1.22-TEST.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6407561/VITA-Homebrew-Sorter-1.22-TEST.zip) Also I'd recommend manually backing up your app.db just incase.

**Comment by v1ru555** [comment]
> > > > I have the same issue, have 1.21 and i always had libshacccg.suprx in my data folder due to GTASA. I see the Kyuhen contest screen, then C2-12828-1 crash.
> > > 
> > > 
> > > Your issue is different since you actually get to the splash screen. Can you send your app.db?
> > 
> > 
> > Attached
> > [app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6372263/app.zip)
> 
> Okay this was happening because one of the apps "power" (I believe you're on a PS TV?) doesn't have a title, nor a titleId or a reservedID. Now if it doesn't find the first reserved ID, it'll look for the second, so this time it should work. If you can confirm its fixed please try this and let me know:
> [VITA-Homebrew-Sorter-1.22-TEST.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6407561/VITA-Homebrew-Sorter-1.22-TEST.zip) Also I'd recommend manually backing up your app.db just incase.

Yes I am on PS TV, and yes the test one does get me past the splash screen crash, many thanks!

**Comment by kamilb880** [comment]
Issue is back on v-1.23, yet this time app opens splash screen. Error occurrs a few seconds later.

FW 3.60 (Enso), app.db and error psp2dmp files attached.

[C2-12828-1.zip.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/7005852/C2-12828-1.zip.zip)

**Comment by joel16** [comment]
> Issue is back on v-1.23, yet this time app opens splash screen. Error occurrs a few seconds later.
> 
> FW 3.60 (Enso), app.db and error psp2dmp files attached.
> 
> [C2-12828-1.zip.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/7005852/C2-12828-1.zip.zip)

Sorry, I was busy last week. I tried your app.db on my device and its working and sorting fine. Here's some steps to make sure you're doing it right:

1) Make sure you have libshacccg.suprx extracted (follow this [guide](https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx) if you haven't, but looking at the fact that you have GTA games in your app.db I assume you do)

2) Restart your vita so that it can refresh your app.db for any changes before you run Vita homebrew sorter.

**Comment by saylla** [comment]
Esse erro aparece após a execução entre 20 a 30 minutos jogando o meu da erro no Battlefield 2 port para o vita
