### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MarcoDjallo** [joel16/VITA-Homebrew-Sorter#4]
Hello, everytime I try to launch the app, I obtain the error C2-12828-1.

I have a PS VITA 2000 with SD2VITA, mounted using YAMT.

Anything I can do to understand why this is happening?

Thanks

**Comment by joel16** [comment]
Sorry been quite busy lately. Can you send a copy of your app.db? Also maybe try this release attached here: https://github.com/joel16/VITA-Homebrew-Sorter/files/6407561/VITA-Homebrew-Sorter-1.22-TEST.zip

I should probably go around and update this

**Comment by jlewery** [comment]
Hello, I've been having the same issue but a Vita 1000 with SD2VITA and YAMT. I've tried the above release but it's still giving me the same error. Attached the app.db if you'd like to take a look.
Thanks!
[app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6547620/app.zip)

**Comment by joel16** [comment]
I'll take a look when I get time, thanks.

**Comment by MarcoDjallo** [comment]
Unfortunately neither the test release works, here's my app.db

thanks!

[app.zip](https://github.com/joel16/VITA-Homebrew-Sorter/files/6574238/app.zip)

**Comment by joel16** [comment]
I think I figured out why you both are getting this issue. You guys are missing libshaccg.suprx since newer versions of vitaGL requires that. Use this: https://github.com/OsirizX/ShaRKF00D/releases/download/1.3/ShaRKF00D.vpk
Install that, and run that and it will extract your libshaccg.suprx to the right folder and then you can delete that app and try opening VITA Homebrew Sorter. Please install the most recent release: https://github.com/joel16/VITA-Homebrew-Sorter/releases/tag/v1.22

**Comment by jlewery** [comment]
Thanks for this. So I still had an issue but looking up ShaRKF00D it requires PSM runtime 2.01 which I didn't have on my Vita. Once I got this on it, then ran ShaRKF00D the app loaded no problem :)

**Comment by joel16** [comment]
Oh whoops yeah. Please use this guide first: https://samilops2.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx and then use the latest release.
